### ISSUE TITLE
Undefined citations error

### ISSUE THREAD

**Issue by madelinebossi** [andrasbarany/cascadilla-xelatex-biblatex#3]
I'm using the style file in Overleaf and keep getting undefined citations errors ("You have cited something which is not included in your bibliography. Make sure that the citation (\cite{...}) has a corresponding key in your bibliography, and that both are spelled the same way."). 

I know that my citation keys are in my bib file, I turned on natbib compatibility mode for biblatex, and I'm using the right citation commands. I've also added the biblatex-unified bbx and cbx files to my Overleaf project, so I'm a bit stumped about what's going wrong here.

**Comment by andrasbarany** [comment]
If you send me your files or give me access to the overleaf document, I'll take a look!

**Comment by madelinebossi** [comment]
I just added you to the overleaf doc, thanks so much!

**Comment by andrasbarany** [comment]
I tried to compile your files locally and I realised that running `biber` failed. On my computer, it crashed because of your entry Woolford:2006, the “θ” character in the abstract of the entry seems to have been the problem. Removing that entry, removing the character, or changing it to Unicode θ seems to fix it. 

Can you try and let me know if that works for you?

**Comment by madelinebossi** [comment]
That fixed it! Thank you so much!
